; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blackpill_f103c8]
platform = ststm32
board = blackpill_f103c8
framework = stm32cube

build_src_filter =
    +<*>
    +<../drivers/Core/Src/*>
    -<../drivers/Core/Src/main.c>
    +<../drivers/Drivers/**>

build_flags =
    -I drivers/Core/Inc
    -I drivers/Drivers/STM32F1xx_HAL_Driver/Inc
    -I drivers/Drivers/CMSIS/Device/ST/STM32F1xx/Include
    -I drivers/Drivers/CMSIS/Include

    -std=gnu++17
    -fno-exceptions
    -fno-rtti

upload_protocol = stlink
debug_tool = stlink

monitor_speed = 115200