; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

build_type = debug

; platform_packages = toolchain-gccarmnoneeabi

debug_build_flags = -Os -g
build_flags = 
	-D HSE_VALUE=8000000U
	-D USE_HAL_DRIVER
	-std=gnu++17
	-fno-strict-aliasing
	; -I Drivers/STM32F1xx_HAL_Driver/Inc
	; -I Drivers/STM32F1xx_HAL_Driver/Inc/Legacy
	; -I Drivers/CMSIS/Device/ST/STM32F1xx/Include
	; -I Drivers/CMSIS/Include
	-I include
	-I Core/Inc
	-I Middlewares/Third_Party/FreeRTOS/Source/include
	-I Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
	-I Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3
	-I src/app
	-I src/services/sim7000
	-I src/services/gps
	-fno-strict-aliasing -Os
	; -Wl,--no-warn-rwx-segments
	-fno-exceptions
	-Wl,--gc-sections

build_src_filter = 
	+<*>
	+<../Core/Src>
	+<../Core/Startup>
	; +<../Drivers/STM32F1xx_HAL_Driver/Src>
	+<../Middlewares/Third_Party/FreeRTOS/Source>


; board_build.ldscript = STM32F103C8TX_FLASH.ld
upload_protocol = stlink
debug_tool = stlink
; monitor_speed = 115200

extra_scripts = post:run_swo.py